sudo: false
language: ruby
rvm:
  - 2.2.7
env:
  - DB=postgresql
addons:
  postgresql: '9.6'
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:schema:load
  - bundle exec rspec
before_install:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/initializers/rails_api_auth.rb.dist config/initializers/rails_api_auth.rb
  - cp config/secrets.yml.dist config/secrets.yml
