sudo: false
language: ruby
rvm:
  - 2.4.1
addons:
  postgresql: "9.6.9"
services:
  - postgresql
before_install:
  - cd api-server
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/secrets.yml.dist config/secrets.yml
  - gem install bundler:2.0.1
script:
  - bundle install
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec ./spec/requests
